/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportSelection.java
 *
 * Created on 11-mei-2012, 0:16:27
 */
package view.Reports;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 *
 * @author Thom
 */
public class ReportSelection extends javax.swing.JFrame {
    
    final private String reportType;

    /** Creates new form ReportSelection */
    public ReportSelection(String reportType) {
        this.reportType = reportType;
        initComponents();
        insertControls();
    }
    
    private void insertControls(){
        final JLabel lblStartDate;
        final JTextField txtStartDate;
        final JLabel lblEndDate;
        final JTextField txtEndDate;
        if(this.reportType == "ThisMonthsOrders"){
            lblStartDate = new JLabel();
            lblStartDate.setText("Startdatum");
            lblStartDate.setBounds(15, 20, 200, 20);
            this.getContentPane().add(lblStartDate);

            txtStartDate = new JTextField();
            txtStartDate.setBounds(115, 20, 150, 20);
            this.getContentPane().add(txtStartDate);

            lblEndDate = new JLabel();
            lblEndDate.setBounds(15, 60, 200, 20);
            lblEndDate.setText("Einddatum");
            this.getContentPane().add(lblEndDate);

            txtEndDate = new JTextField();
            txtEndDate.setBounds(115, 60, 150, 20);
            this.getContentPane().add(txtEndDate);
        }
        else if(this.reportType == "OrdersByHour"){
            lblStartDate = new JLabel();
            lblStartDate.setText("Startdatum");
            lblStartDate.setBounds(15, 20, 200, 20);
            this.getContentPane().add(lblStartDate);

            txtStartDate = new JTextField();
            txtStartDate.setBounds(115, 20, 150, 20);
            this.getContentPane().add(txtStartDate);
        }
        else
        {
            lblStartDate = null;
            txtStartDate = null;
            lblEndDate = null;
            txtEndDate = null;
        }
        
        JButton btnSubmit = new JButton();
        btnSubmit.setText("Afdrukken");
        btnSubmit.setBounds(85, this.getHeight() - 80, 120, 20);
        btnSubmit.addActionListener(  
        new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent event) {   
                main.PASApplication.getQueryManager().deleteReportParameter(reportType);
                main.PASApplication.getQueryManager().insertReportParameter(reportType, "StartDate", txtStartDate.getText());                 
                if(reportType == "ThisMonthsOrders") main.PASApplication.getQueryManager().insertReportParameter(reportType, "EndDate", txtEndDate.getText());
                try
                {
                    java.awt.Desktop.getDesktop().open(new java.io.File("C:\\" + reportType + ".accdb"));
                }
                catch(java.io.IOException e)
                {
                    System.out.println("Het rapport kan niet worden geopend in Access.");
                } 
            }  
        }  
        ); 
        this.getContentPane().add(btnSubmit);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
