package view.Members;

import java.awt.event.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * This panel checks in or out a member
 * @author Vincent Ratterman
 */
public class CheckInOut extends javax.swing.JPanel {

    /** Creates new form LidZoeken */
    public CheckInOut() {
        initComponents();

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblActiviteit = new javax.swing.JLabel();
        lblVestiging = new javax.swing.JLabel();
        lblPasnummer = new javax.swing.JLabel();
        cmbActiviteit = new javax.swing.JComboBox();
        cmbVestiging = new javax.swing.JComboBox();
        txtPasnummer = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("In-/uitchecken");

        lblActiviteit.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblActiviteit.setText("Activiteit:");

        lblVestiging.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblVestiging.setText("Vestiging:");

        lblPasnummer.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblPasnummer.setText("Pasnummer:");

        cmbActiviteit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inchecken/Uitchecken FitShape" }));

        cmbVestiging.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FitShape Alkmaar", "FitShape Haarlem", "FitShape Purmerend" }));

        txtPasnummer.setToolTipText("");
        txtPasnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasnummerKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblActiviteit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVestiging))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbVestiging, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbActiviteit, 0, 250, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPasnummer)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(txtPasnummer))))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActiviteit)
                    .addComponent(cmbActiviteit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVestiging)
                    .addComponent(cmbVestiging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasnummer)
                    .addComponent(txtPasnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblResult)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    /*
     * When text is filled in in txtPasnummer, handle the check in/out
     * @param evt KeyEvent object of event
     */
    private void txtPasnummerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasnummerKeyPressed
        int key = evt.getKeyCode();
        String vestigingscode = "";

        if (key == KeyEvent.VK_ENTER) {
            switch (cmbVestiging.getSelectedIndex()) {
                case 0:
                    vestigingscode = "alk";
                    break;
                case 1:
                    vestigingscode = "haa";
                    break;
                case 2:
                    vestigingscode = "pur";
                    break;
            }
            try {
                lblResult.setText(main.PASApplication.getQueryManager().pasCheckInUit(txtPasnummer.getText(), vestigingscode));
            } catch (SQLException ex) {
                Logger.getLogger(CheckInOut.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtPasnummer.setText("");
        }
    }//GEN-LAST:event_txtPasnummerKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbActiviteit;
    private javax.swing.JComboBox cmbVestiging;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblActiviteit;
    private javax.swing.JLabel lblPasnummer;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblVestiging;
    private javax.swing.JTextField txtPasnummer;
    // End of variables declaration//GEN-END:variables
}
