package view.Members;

import view.Accounts.AccountSearch;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import view.MainFrame;

/**
 * 
 * @author Vincent
 */
public class CourseRegistration extends javax.swing.JPanel {

    private JTable table;
    private String selectedCursus = "";

    /** Creates new form CursusInschrijving */
    public CourseRegistration() {
        initComponents();
        loadTable();
    }

    private void loadTable() {
        String[] columnNames = {"Cursusnr",
            "Cursusnaam",
            "Max. deelnemers",
            "Startdatum",
            "Einddatum",
            "Ingeschreven"
        };
        try {
            DefaultTableModel model = new DefaultTableModel(main.PASApplication.getQueryManager().getCursusList(), columnNames) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            table = new JTable(model);

            table.getColumnModel().getColumn(0).setMinWidth(120);
            table.getColumnModel().getColumn(1).setMinWidth(70);
            table.getColumnModel().getColumn(2).setMinWidth(80);
            table.getColumnModel().getColumn(3).setMinWidth(100);
            table.getColumnModel().getColumn(4).setMinWidth(100);

            table.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    selectedCursus = table.getValueAt(table.rowAtPoint(e.getPoint()), 0).toString();
                }
            });

            final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);
            table.setRowSorter(sorter);


            JScrollPane scrollPane = new JScrollPane(table);
            scrollPane.setSize(800, 300);

            this.add(scrollPane);
        } catch (SQLException ex) {
            Logger.getLogger(AccountSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_CursusInschrijving = new javax.swing.JLabel();
        lbl_pasnummer = new javax.swing.JLabel();
        txt_pasnummer = new javax.swing.JTextField();

        lbl_CursusInschrijving.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbl_CursusInschrijving.setText("Cursus inschrijving");

        lbl_pasnummer.setText("Pasnummer: ");

        txt_pasnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pasnummerKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(838, 838, 838)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pasnummer)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_pasnummer, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_CursusInschrijving, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_CursusInschrijving)
                .addGap(7, 7, 7)
                .addComponent(lbl_pasnummer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pasnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pasnummerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pasnummerKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            Component frame = null;
            try {
                if ("".equals(selectedCursus)) {
                    JOptionPane.showMessageDialog(frame, "Selecteer eerst een cursus aub");
                    return;
                }
                else {
                    JOptionPane.showMessageDialog(frame, main.PASApplication.getQueryManager().cursusInschrijving(txt_pasnummer.getText(), selectedCursus));           
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(CheckInOut.class.getName()).log(Level.SEVERE, null, ex);
            }
            MainFrame.changePanel(MainFrame.CURSUSINSCHRIJVING);
            MainFrame.addPanel(new CourseRegistration(), MainFrame.CURSUSINSCHRIJVING);
            
            
            txt_pasnummer.setText("");
        }
    }//GEN-LAST:event_txt_pasnummerKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_CursusInschrijving;
    private javax.swing.JLabel lbl_pasnummer;
    private javax.swing.JTextField txt_pasnummer;
    // End of variables declaration//GEN-END:variables
}
