package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * @author Thom Puiman
 * This frame is showed first to identify the current user.
 */
public class Login extends javax.swing.JFrame {

    /* 
     * True when the user has access to the application, false if not
     */
    private boolean hasAccess = false;
    /*
     * True if the user requested to exit the application
     */
    private boolean closeApp = false;
    /*
     * Contains the supplied employeecode
     */
    public static int employeecode = 0;

    /** Creates new form LoginScherm */
    public Login() {
        super("Fitshape medewerkers administratie");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        jButton1Login = new javax.swing.JButton();
        jButton2Anuleren = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1Gebruikn = new javax.swing.JLabel();
        jLabel2WW = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        txtUsername.setForeground(new java.awt.Color(255, 102, 204));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jButton1Login.setText("Login");
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });

        jButton2Anuleren.setText("Annuleren");
        jButton2Anuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2AnulerenActionPerformed(evt);
            }
        });

        txtPassword.setForeground(new java.awt.Color(255, 102, 204));
        txtPassword.setToolTipText("");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        jLabel1Gebruikn.setText("Medewerkersnr.");

        jLabel2WW.setText("Wachtwoord");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/FitShape_Logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1Login, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2Anuleren))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1Gebruikn)
                            .addComponent(jLabel2WW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Gebruikn)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2WW)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2Anuleren)
                            .addComponent(jButton1Login))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @author Thom/Oscar
     * @param evt deze JButton zorgt met deze methode dat de gruikers gegevens worden gecontroleerd uit de query manager met de methode checkMedewerker
     */
    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed

        if (main.PASApplication.getQueryManager().checkMedewerker(this.txtUsername.getText(), new String(this.txtPassword.getPassword()))) {
            this.hasAccess = true;
            employeecode = Integer.parseInt(txtUsername.getText());

        } else {
            JOptionPane.showMessageDialog(null, "Ongeldige medewerkerscode en/of wachtwoord.");
        }
    }//GEN-LAST:event_jButton1LoginActionPerformed

    private void jButton2AnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2AnulerenActionPerformed
        this.closeApp = true;
    }//GEN-LAST:event_jButton2AnulerenActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();

    if (key == KeyEvent.VK_ENTER) {
            if (main.PASApplication.getQueryManager().checkMedewerker(this.txtUsername.getText(), new String(this.txtPassword.getPassword()))) {
                this.hasAccess = true;
                this.employeecode = Integer.parseInt(txtUsername.getText());

            } else {
                JOptionPane.showMessageDialog(null, "Ongeldige gebruikersnaam en/of wachtwoord.");
            }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public boolean gethasAccess() {
        return hasAccess;
    }

    public boolean getcloseApp() {
        return closeApp;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Login;
    private javax.swing.JButton jButton2Anuleren;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Gebruikn;
    private javax.swing.JLabel jLabel2WW;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
