/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountZoeken.java
 *
 * Created on 30-mei-2012, 21.00
 */
package view.Accounts;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import view.MainFrame;

/**
 * A user can search for accounts and access the modify screen from here
 * @author Vincent S
 */
public class AccountSearch extends javax.swing.JPanel {

    /*
     * JTable for displaying all accounts
     */
    private JTable table;

    /** Creates new form AccountZoeken */
    public AccountSearch() {
        initComponents();
        this.lblNotFound.setVisible(false);
        loadTable();
    }

    /*
     * Get data of the account and add this to the JTable
     */
    private void loadTable() {
        String[] columnNames = {"Medewerkersnummer",
            "Geslacht",
            "Voornaam",
            "Tussenvoegsel",
            "Achternaam",
            "Wachtwoord",
            "Vestigingscode",
            "Rolcode",
            "Status"
        };
        try {
            DefaultTableModel model = new DefaultTableModel(main.PASApplication.getQueryManager().getAccountList(), columnNames) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            table = new JTable(model);

            table.getColumnModel().getColumn(0).setMinWidth(120);            

            final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);
            table.setRowSorter(sorter);

            txtSearchAchternaam.addKeyListener(new KeyListener() {

                public void keyReleased(KeyEvent e) {
                    String text = txtSearchAchternaam.getText();
                    if (text.length() == 0) {
                        sorter.setRowFilter(null);
                    } else {
                        try {
                            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, 4));
                            if (table.getRowCount() == 0) {
                                lblNotFound.setVisible(true);
                                repaint();
                            } else {
                                lblNotFound.setVisible(false);
                                repaint();
                            }
                        } catch (PatternSyntaxException pse) {
                            System.err.println("Bad regex pattern");
                        }
                    }
                }

                public void keyTyped(KeyEvent e) {
                    // TODO: Do something for the keyTyped event
                }

                public void keyPressed(KeyEvent e) {
                    // TODO: Do something for the keyPressed event
                }
            });
            
            table.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    if (e.getClickCount() == 2) {
                        MainFrame.setAccountModify(Integer.parseInt(table.getValueAt(table.rowAtPoint(e.getPoint()), 0).toString()));
                        MainFrame.changePanel(MainFrame.ACCOUNT);
                    }
                }
            });
            
            JScrollPane scrollPane = new JScrollPane(table);
            scrollPane.setSize(new Dimension(750,600));
           
            this.pnlData.setLayout(new GridLayout());
            this.pnlData.add(scrollPane, BorderLayout.EAST);
            this.pnlData.setSize(750, 600);
            
        } catch (SQLException ex) {
            Logger.getLogger(AccountSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean loadModify() {

        return true;
    }

    public static void reloadTable() {

    }
           
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchAchternaam = new javax.swing.JTextField();
        lblNotFound = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlData = new javax.swing.JPanel();

        jLabel1.setText("Zoek op achternaam:");

        lblNotFound.setForeground(new java.awt.Color(255, 0, 0));
        lblNotFound.setText("Selectie niet gevonden!");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblNotFound)
                .addContainerGap(527, Short.MAX_VALUE))
            .addComponent(pnlData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNotFound)
                    .addComponent(txtSearchAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            String[] columnNames = {"Medewerkersnummer",
            "Geslacht",
            "Voornaam",
            "Tussenvoegsel",
            "Achternaam",
            "Wachtwoord",
            "Vestigingscode",
            "Rolcode",
            "Status"
        };

        try {
            // TODO add your handling code here:
            DefaultTableModel model = new DefaultTableModel(main.PASApplication.getQueryManager().getAccountList(), columnNames) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
                
            };
             model.fireTableDataChanged();
             table.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(AccountSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNotFound;
    private javax.swing.JPanel pnlData;
    private javax.swing.JTextField txtSearchAchternaam;
    // End of variables declaration//GEN-END:variables
}
